version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    cooldown:
      semver-patch-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      semver-patch-days: 7
    groups:
        action-deps:
          patterns:
            - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      dev-dependencies:
        dependency-type: development
    cooldown:
      semver-patch-days: 7
