repos:
  - repo: local
    hooks:
      - id: oxfmt
        name: Check formatting with oxfmt
        language: system
        entry: pnpm run fmt:check
        types_or: [javascript, ts, tsx]
      - id: oxlint
        name: Lint with oxlint
        language: system
        entry: pnpm run lint
        types_or: [javascript, ts, tsx]
