require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - vendor/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - "*.gemspec"

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 200

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FetchEnvVar:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/FilePath:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/SpecFilePathFormat:
  Enabled: false
