---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - bin/*
  - vendor/bundle/**/*
require:
  - dry/cli
  - fileutils
  - parallel
  - pathname
  - rspec
domains: []
reporters:
  - rubocop
  - require_not_found
  - update_errors
plugins:
  - solargraph-rspec
require_paths: []
max_files: 5000
